### ISSUE TITLE
Carousel In testimonial

### ISSUE THREAD

**Issue by mukilan2815** [dvjsharma/Drawn2Shoe#104]
**Describe the new feature**
We can add carousel in testimonial section.
![image](https://github.com/dvjsharma/Drawn2Shoe/assets/71129858/80a1d1e9-06c8-4d2c-a5a1-5722613e1e65)

**Additional context**
Assign this under GSSOC'24

**Comment by dvjsharma** [comment]
I don't think this will be required. WDYT @ShashankShekhar07?
