### ISSUE TITLE
Update the react-router-dom to the latest version v6.4 making it more convenient for the developers

### ISSUE THREAD

**Issue by MinavKaria** [dvjsharma/Drawn2Shoe#107]
**Is your feature request related to a problem? Please describe.**
The current routing setup is cumbersome and difficult to manage due to the older version of React Router DOM.

**Describe the solution you'd like**
Update React Router DOM to v6, using createBrowserRouter and RouterProvider for a more efficient routing setup. This will simplify nested routes and improve code maintainability.

**Describe alternatives you've considered**
- Continuing with the older version, which is not sustainable due to deprecated features.
- Using a different routing library, requiring a significant rewrite.

_GSSOC'2024 Contribuitor_

@dvjsharma Please assign this to me

**Comment by dvjsharma** [comment]
Thanks for the ticket @MinavKaria. We have decided that we'll stick to the current version.

**Comment by MinavKaria** [comment]
Ok , Thanks for acknowledging
