### ISSUE TITLE
Add 'Back-To-Top' Button

### ISSUE THREAD

**Issue by AsmitaMishra24** [dvjsharma/Drawn2Shoe#110]
The addition of a "Back to Top" button on the homepage of our website would enhance user experience by providing a convenient way for users to quickly return to the top of the page after scrolling down. This feature is commonly seen on many websites and has become an expected element for smooth navigation.

https://github.com/dvjsharma/Drawn2Shoe/assets/146121869/d0197ab3-1645-4606-a452-741e36c36d3f

**Comment by dvjsharma** [comment]
Go ahead @AsmitaMishra24 . A minor improvement I recommend is to make the button visible only when the user is scrolling down, not at the first frame itself. Also, FYI we already have scroll to top functionality when route changes. #78

**Comment by dvjsharma** [comment]
updaes @AsmitaMishra24
