### ISSUE TITLE
Adding a Horizontal scroll on the Customer feedback section or Carousel of the home page

### ISSUE THREAD

**Issue by KARANSINGH34951** [dvjsharma/Drawn2Shoe#115]
**Describe the bug**
It would be better to add some more customers feedback with horizontal scroll effect to make it more dynamic website

**Steps To Reproduce**
1. Go to ''Homepage
3. Scroll down to bottom carosel
4. See the static section

**Expected behavior**

https://github.com/dvjsharma/Drawn2Shoe/assets/137412876/206a8eba-2775-4a36-9ae0-4d58635312d6

**Comment by dvjsharma** [comment]
We tried this already, didn't work out with the design team. Closing, please re-open if required.
