### ISSUE TITLE
Adding Dark mode Button on the Navbar or Footer

### ISSUE THREAD

**Issue by KARANSINGH34951** [dvjsharma/Drawn2Shoe#116]
**Describe the new feature**
Every modern website has the feature of the dark mode/ night mode it should have the same

**Describe the possible approach**
It can be applied simple with a dark mode button on the navbar or on the footer as per the requirement

**Comment by dvjsharma** [comment]
Already tracked by #96. Closing as duplicate. Please re-open if required.
