### ISSUE TITLE
feat: Add ORM to backend code

### ISSUE THREAD

**Issue by dvjsharma** [dvjsharma/Drawn2Shoe#117]
**Describe the new feature**
Currently, we use plain nodejs backend for handling requests and a SQL based DB. But this makes app sharing very challenging as DB is not reflected in code itself. 

**Describe the possible approach**
Add ORM models in the code, enabling new DB migration and creation steps.

**Additional context**
There are many good ORM libs available for nodejs. One such is [prisma](https://www.npmjs.com/package/prisma).

**Comment by dvjsharma** [comment]
This issue is open for all, PTAL and let us know if you want to work on this.

**Comment by kaali001** [comment]
hey @dvjsharma,  I would like to work on this issue.

**Comment by dvjsharma** [comment]
Go ahead @kaali001

**Comment by kaali001** [comment]
Hey @dvjsharma,  I have implemented Prisma ORM , Please provide me the testing documents of functionalities , if you have.

**Comment by dvjsharma** [comment]
Closing against #138
