### ISSUE TITLE
categories 

### ISSUE THREAD

**Issue by riyasaxena32** [dvjsharma/Drawn2Shoe#120]
on clicking categories no categories are visible...kindly assign it to me..i wana add some categories menu bar

**Comment by dvjsharma** [comment]
Hmm that points to a bug in your DB connection. You should see 3 shoe categories in that tab. Please re-check your database connectivity and try again.

**Comment by dvjsharma** [comment]
![image](https://github.com/dvjsharma/Drawn2Shoe/assets/119073504/9fe1b03d-f0ed-4067-a5bc-ca36a17e2163)

Just checked with the latest master. Everything is working as expected. Please check your database connection and try again.

Closing the issue.
