### ISSUE TITLE
Make navbar sections bold instead underline when selected

### ISSUE THREAD

**Issue by dvjsharma** [dvjsharma/Drawn2Shoe#124]
## Description

![image](https://github.com/dvjsharma/Drawn2Shoe/assets/119073504/f8208421-19fb-463f-bf1c-1ae35d81ee6b)

When any of these page is requested, the navbar shows underling under the name to mark selection. Change this to bold.

**Comment by riyasaxena32** [comment]
please assign me

**Comment by dvjsharma** [comment]
Hey @riyasaxena32. I see a few issues already assigned under your name. Please complete them on priority so we can assign you more tickets. Hope you understand.
Thanks

**Comment by gl-cardillo** [comment]
can i get this?

**Comment by dvjsharma** [comment]
Go ahead @gl-cardillo

**Comment by gl-cardillo** [comment]
I made the pull request @dvjsharma #137
