### ISSUE TITLE
Button colour does not change when clicked

### ISSUE THREAD

**Issue by dvjsharma** [dvjsharma/Drawn2Shoe#125]
## Description

![image](https://github.com/dvjsharma/Drawn2Shoe/assets/119073504/a027339c-50cd-4b1e-a4e0-9201d5c1200b)

When we click on any white background button through the UI (in above example, the login button) the background changes to black and remains black. This bug needs to be fixed for all buttons in the UI.

**Comment by riyasaxena32** [comment]
assign this to me..i want to work on it

**Comment by dvjsharma** [comment]
Hey @riyasaxena32. I see a few issues already assigned under your name. Please complete them on priority so we can assign you more tickets. Hope you understand.
Thanks

**Comment by riyasaxena32** [comment]
completed..now please assign me

**Comment by gl-cardillo** [comment]
Hello @dvjsharma , If this issue is still open I would like to be assigned.

**Comment by dvjsharma** [comment]
Go ahead @gl-cardillo.
