### ISSUE TITLE
Change Favicon

### ISSUE THREAD

**Issue by dvjsharma** [dvjsharma/Drawn2Shoe#126]
## Description

![image](https://github.com/dvjsharma/Drawn2Shoe/assets/119073504/06b3a578-84ed-41ee-845b-d3c2ced07f57)

The existing favicon, 'drawn2shoe' horizontal logo, does not fit properly. Replace it with the hero image on the homepage.

![image](https://github.com/dvjsharma/Drawn2Shoe/assets/119073504/ebb564ee-9142-47fd-9177-41152afb762f)

Find the high quality image in assets

**Comment by GeorgiosDrivas** [comment]
Hello @dvjsharma ! I would like to work on this issue.

**Comment by dvjsharma** [comment]
Go ahead @GeorgiosDrivas

**Comment by kaali001** [comment]
Hey @dvjsharma , Assign this issue to me.

**Comment by dvjsharma** [comment]
Go ahead @kaali001

**Comment by kaali001** [comment]
Hey @dvjsharma  , I tried below images and got as result , please let me know if you have any preferences, I would suggest for 2 or 3.

1)  
![Screenshot 2024-07-17 205912](https://github.com/user-attachments/assets/4a0d6e58-1ed3-4bf8-b546-b7982bb30a79)

![banner-hero (1)](https://github.com/user-attachments/assets/f6530160-0f33-473a-acc0-63077d60489c)


2)  
![Screenshot 2024-07-17 211242](https://github.com/user-attachments/assets/2a6f4e2d-ee88-4d4e-ba2c-2b44d356e826)
![banner-hero__1_-removebg-preview (4)](https://github.com/user-attachments/assets/43512197-39f5-420f-9a8a-110eeaf9d4bf)


3) 
![Screenshot 2024-07-17 212204](https://github.com/user-attachments/assets/14b35ac8-5151-4a3a-8af6-82688993e5ee)
![converse1-removebg-preview](https://github.com/user-attachments/assets/38fc9341-5571-44f6-87fe-7d55804f076d)

**Comment by dvjsharma** [comment]
2 looks good, but it’ll look better if you make it a round image (same as 1, not stretched tho).

**Comment by kaali001** [comment]
Hey @dvjsharma , I tried hard on this to figure out the problem and I found out that the icon should not contains any side margin of round icon. Below is the fixed one : 

![image](https://github.com/user-attachments/assets/decfd939-118e-4ddd-b6cd-9bc19224ecd8)

![image](https://github.com/user-attachments/assets/65b7d338-0f68-446c-a4c8-8b6ce95f2988)


Now I'm making PR.

**Comment by dvjsharma** [comment]
Looks good, go ahead @kaali001.
