### ISSUE TITLE
Payment gateway UI bug

### ISSUE THREAD

**Issue by dvjsharma** [dvjsharma/Drawn2Shoe#129]
## Description

![image](https://github.com/dvjsharma/Drawn2Shoe/assets/119073504/5fd0f0c6-ec25-4e72-93c7-0bd6d5e35d5d)

As soon as a logged in user enters cart, payment gateway automatically pops up without any clicks. Needs to be fixed.

**Comment by dvjsharma** [comment]
Also, the `increase count` button is not working.

![image](https://github.com/dvjsharma/Drawn2Shoe/assets/119073504/2b853a2f-8784-4d7e-a4ad-04c019c35ac6)

**Comment by Mehdi-Messaadi** [comment]
Hi!
**I'd love to work on the first issue, please.**
As for the second problem (the increase count button not working), I believe it should have its own separate issue. Thoughts?

**Comment by dvjsharma** [comment]
Go ahead @Mehdi-Messaadi, and yes tracking 2 tickets makes sense.

**Comment by dvjsharma** [comment]
Closing as fixed by #133. Making a new issue for `count` not working.
