### ISSUE TITLE
Registration Page

### ISSUE THREAD

**Issue by Yashop181** [dvjsharma/Drawn2Shoe#130]
Describe the bug
The registration form is too large and not fitting well within the viewport, causing layout issues.

Steps To Reproduce

Go to the registration page.
Click on the 'Register' button to open the registration form.
Scroll down to view the entire form.
See error: The form extends beyond the viewport and requires scrolling.
Expected behavior
The registration form should fit within the viewport without the need for scrolling, providing a seamless user experience.

Screenshots
Initial problematic layout:
![Screenshot (1127)](https://github.com/dvjsharma/Drawn2Shoe/assets/108663055/377e35c1-8a48-4338-8936-c65c48a81093)

Proposed improved layout:
![Screenshot (1125)](https://github.com/dvjsharma/Drawn2Shoe/assets/108663055/72e1558a-2ec3-4fa5-aade-d45ca2852d66)

Desktop (please complete the following information):

OS: Windows 10
Browser: Chrome
Version: 114.0.5735.199
Additional context
This issue can be fixed by adjusting the CSS styles to ensure the form's size is responsive and fits within the viewport on various screen sizes.

**Comment by dvjsharma** [comment]
Hey @Yashop181. Thanks for pointing out. We are already tracking this by #118. Closing as duplicate.
