### ISSUE TITLE
Feature Request: Add User Profile Page

### ISSUE THREAD

**Issue by kaali001** [dvjsharma/Drawn2Shoe#143]
**Describe the new feature**
I would like to request the addition of a user profile page to the project. This is important because it enhances the user experience by allowing users to view and manage their personal information, order history, and other relevant details.

**Describe the possible approach**

- Personal Information: Display and allow users to edit their name, email, phone number, and shipping address.
- Order History: Display a list of past orders with details such as order number, date, items purchased, and status.
- Wishlist: Allow users to view and manage items they have added to their wishlist/cart.
- Account Settings: Provide options for users to change their password, manage payment methods, and set preferences.

**Implementation Suggestions:**

- Frontend: Use React components to create the user profile page, integrating it into the existing navigation structure.
- Backend: Add endpoints to handle fetching and updating user information, order history, and account settings.

**Comment by kaali001** [comment]
Hey @dvjsharma , I would like to on this feature.

**Comment by dvjsharma** [comment]
Hello @kaali001, would be good. Please go ahead. Make sure to follow the current project theme, and export the DB schema if you'll be making any changes there.

**Comment by kaali001** [comment]
hey @dvjsharma , I am adding a border on navbar for better UI, please let me know if this matter. 

![image](https://github.com/user-attachments/assets/9193457d-ffd9-4178-9ab7-26dc929da547)

**Comment by dvjsharma** [comment]
No issues @kaali001. We can always revert back if it doesn't look good at the end.

**Comment by dvjsharma** [comment]
Closing against #150. Please create new ticket for additional tasks.
