### ISSUE TITLE
issue: Missing Email Validation in Login System

### ISSUE THREAD

**Issue by kaali001** [dvjsharma/Drawn2Shoe#152]
### Describe the bug

The current login system lacks proper email validation beyond the basic HTML5 validation. This allows users to potentially create accounts with invalid or fake email addresses, leading to issues such as:

 - Spam account creation
 - Invalid email entries in the user database
 - Difficulties in user communication and account recovery

### Steps To Reproduce

1. Navigate to the registration page.
2. Enter an invalid or non-existent email address (e.g., "invalidemail@", "user@domain", etc.) using developer tools to bypass HTML5 validation.
3. Complete the registration process.
4. Observe that the account is created without any validation error.

### Expected behavior

The system should enforce email validation to ensure that users enter a valid email address and verify it by sending a confirmation link or OTP mail.

### Proposed Solution:

Implement an email verification process to ensure users enter a valid and active email address. This can be achieved by:

1. Sending a confirmation email containing a verification link that users must click to activate their account.
2. Sending a one-time password (OTP) to the entered email address that users must enter on the site to complete the registration process.

**Comment by kaali001** [comment]
@dvjsharma , Assign me this issue.

**Comment by dvjsharma** [comment]
Instead getting a one-time password, I'll suggest getting a magic link with some sort of state and code to validate the user. Also, keep in mind that if an inactive user tries to login, they are displayed an error of account activation via toasts or whichever way you prefer to use. You can go ahead with this issue, I'll add the level once you raise a PR.

**Comment by kaali001** [comment]
Hey @dvjsharma , Actually all the ecommerce site use OTP method for account creation because that is more convenient to user rather clicking on a link.

**Comment by kaali001** [comment]
@dvjsharma , let me know your preference.

**Comment by kaali001** [comment]
Implementing confirmation email containing a verification link .

**Comment by dvjsharma** [comment]
closing against #155
