### ISSUE TITLE
issue: Customize Page Allows Form Submission Without User Authorization

### ISSUE THREAD

**Issue by kaali001** [dvjsharma/Drawn2Shoe#153]
### Describe the bug

The Customize page allows users to submit the form for ordering custom products without being signed in. This results in data being stored in the database without any associated user information, making it impossible to:

- Track the user
- Deliver the custom product
- Communicate with the user regarding their order

### Steps To Reproduce

1. Navigate to the Customize page.
2. Fill in the details of the custom product.
3. Submit the form without signing in.
4. Observe that the form is submitted, and the data is stored in the database without any user information.

### Expected behavior

The system should require users to be signed in before allowing them to submit the customization form. This ensures that all submitted data is associated with a valid user account.

### Actual Behavior:

The system allows the form to be submitted without user authorization, leading to data being stored in the database without any user information.

### Proposed Solution:

Implement an authorization check to ensure that users are signed in before they can submit the customization form. This can be achieved by:

1. Redirecting users to the login page if they attempt to access the Customize page without being signed in.
2. Displaying an appropriate message prompting users to sign in before submitting the form.
3. Associating the submitted data with the user's account to ensure proper tracking and communication.

### Screenshots

![image](https://github.com/user-attachments/assets/96a1d6fc-4727-4f97-8a7b-8a1d9335ce6e)

![image](https://github.com/user-attachments/assets/0b681aa4-ffec-4498-984f-0f1fcea5f064)

![image](https://github.com/user-attachments/assets/a43f750e-8d51-493d-8f6c-818055b9320c)

**Comment by kaali001** [comment]
@dvjsharma , Assign me this issue.

**Comment by dvjsharma** [comment]
Go ahead @kaali001

**Comment by dvjsharma** [comment]
My bad, closed by mistake

**Comment by dvjsharma** [comment]
closing against #154
