### ISSUE TITLE
Add Code of Conduct 

### ISSUE THREAD

**Issue by Princegupta101** [dvjsharma/Drawn2Shoe#17]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by IP80808080** [comment]
Sir please assign this issue to me. Also Sir can you plz label it for level

**Comment by dvjsharma** [comment]
Hey @IP80808080, thank you for your interest. This issue is not available for contributors but is a checkmark for us to make the repo in-line for better contributor onboarding. Keep checking for other issues!

**Comment by dvjsharma** [comment]
Completed by #20
