### ISSUE TITLE
Add validation in the forms 

### ISSUE THREAD

**Issue by siddxharth1** [dvjsharma/Drawn2Shoe#23]
i can add form validation on login and customize page 
can you please assign this issue to me under gssoc

**Comment by dvjsharma** [comment]
Hey @siddxharth1, please go ahead. Make sure to create a separate branch and adhere to code of conduct. You can find the SQL db for the project [here](https://drive.google.com/file/d/1qShqZpEGcdhVmZ7zzAar-tBwhPFomNWW/view?usp=sharing). Ping us if you face any difficulties!
