### ISSUE TITLE
[FEAT]: Redux Auth slice

### ISSUE THREAD

**Issue by Sid-80** [dvjsharma/Drawn2Shoe#26]
## Describe
Adding the redux auth slice for state management of authentication

**Comment by Sid-80** [comment]
@dvjsharma Please assign me this issue under GSSOC24!

**Comment by dvjsharma** [comment]
Hey @Sid-80, Please go ahead. This would be a nice addition for overall state management. The architecture is already in place but needs to be implemented. Feel free to ping me or @ShashankShekhar07 regarding any queries.

**Comment by Sid-80** [comment]
Sure! sir

**Comment by Sid-80** [comment]
@dvjsharma Please review the pull request! Let me know if any changes required!
