### ISSUE TITLE
[FEAT]: Style README.md, CODE_OF_CONDUCT.md, LEARN.md

### ISSUE THREAD

**Issue by kanikaa-3018** [dvjsharma/Drawn2Shoe#27]
i think that the readme and learn files lacks some description, i would like to contribute in the same for GSSoc'24

**Comment by dvjsharma** [comment]
Hi @kanikaa-3018, please proceed. These files are crucial resources for onboarding contributors hence I'm labelling this as high priority task. Feel free to ping me or @ShashankShekhar07 regarding any issues.

**Comment by kanikaa-3018** [comment]
hey, @dvjsharma i have raised a pr, pls check and suggest any changes if needed

**Comment by Me-Nitin** [comment]
@dvjsharma man your labels are incorrect, the gssoc label is correct but lsecond label you have to write in small letters and without space like this level1, level2 etc.....
![Uploading PR.png…]()

**Comment by Me-Nitin** [comment]
![Uploading PR.png…]()

**Comment by dvjsharma** [comment]
Thanks for bringing this up @Me-Nitin. We have fixed it.
