### ISSUE TITLE
[FEAT]: Add Logout Button and its functionality

### ISSUE THREAD

**Issue by ShashankShekhar07** [dvjsharma/Drawn2Shoe#30]
The navbar will display a Logout button only when a user is logged in. Clicking this button will log the user out and the button will disappear.

**Comment by Damini2004** [comment]
Kindly assign this issue to me i wanted to work on it

**Comment by ShashankShekhar07** [comment]
Hey @Damini2004 Please Go ahead.

**Comment by ShashankShekhar07** [comment]
Any Updates?

**Comment by Damini2004** [comment]
Working sir might take longer time..

**Comment by kart2004** [comment]
Hi @ShashankShekhar07, can you please assign this to me ? I think I'll be able to get it done quickly.
Thanks in advance!

**Comment by tanishka786** [comment]
I would like to contribute in this project , so please assign this issue to me .
