### ISSUE TITLE
adding card in catagories

### ISSUE THREAD

**Issue by AnitSarkar123** [dvjsharma/Drawn2Shoe#34]
**Describe the new feature**
i want to add card in catagories options

**Describe the possible approach**
i want to use ui libraries for this

**Describe any alternatives**

**Additional context**

**Comment by dvjsharma** [comment]
Hey @AnitSarkar123, can you please describe what exactly are you suggesting to do?

**Comment by AnitSarkar123** [comment]
Sorry sir I forgot to send the code @dvjsharma
