### ISSUE TITLE
Update README for Improved Documentation

### ISSUE THREAD

**Issue by adarsh-site** [dvjsharma/Drawn2Shoe#36]
Clear and well-structured documentation is crucial for users and contributors to understand the project, its purpose, and how to get started. The current README is not visually appealing. I propose to make it more visually appealing by adding badges for tech stack, visiter count, issue count, fork count and other items.

hey @dvjsharma  , please assign this issue to me.

**Comment by ShashankShekhar07** [comment]
Go ahead @jinx-vi-0

**Comment by adarsh-site** [comment]
hey @dvjsharma , I have created a pr please check it and let me know for any feedback.
