### ISSUE TITLE
Add About Section 

### ISSUE THREAD

**Issue by aasthakourav20** [dvjsharma/Drawn2Shoe#44]
About section provides  clear and concise description of what the project is and also includes the project link .

**Comment by ShashankShekhar07** [comment]
Hey @aasthakourav20 can you describe how and where you will add it?

**Comment by dvjsharma** [comment]
Updates @aasthakourav20

**Comment by aasthakourav20** [comment]
> Updates @aasthakourav20

Hey I have raised a PR kindly check & review .

**Comment by dvjsharma** [comment]
Hey @aasthakourav20. It's better to assign the issue and provide a brief before starting rather than opening a PR. Please remember for next time.

**Comment by aasthakourav20** [comment]
> Hey @aasthakourav20. It's better to assign the issue and provide a brief before starting rather than opening a PR. Please remember for next time.

Sorry for the mistake , I will be more responsible  next time . But any issues with the current PR ? , if any then please tell me how can I help.

**Comment by dvjsharma** [comment]
No worries @aasthakourav20. Will let you know once the design team goes through it.
