### ISSUE TITLE
Enhance readme.md file  and add Learn.md file

### ISSUE THREAD

**Issue by aasthakourav20** [dvjsharma/Drawn2Shoe#46]
Hey @dvjsharma  , A Readme file plays an important role in User/Contributor convenience . It is essential in any given repository because it serves as the primary source of information about the project. It provides an overview of the project's purpose, how to install and use it, and any necessary prerequisites. Additionally, the README often includes guidelines for contributing, links to documentation, and contact information for the maintainers.
Let's create a more descriptive , attention seeking README file including all guidelines .

Kindly assign this issue to me under GSSoC'24 .

**Comment by dvjsharma** [comment]
Hey @aasthakourav20. We do have a decent looking README.md file and LEARN.md file is no longer required. Can you mention the changes you are planning to do?
