### ISSUE TITLE
[Feature Request]: Adding a logo in the title

### ISSUE THREAD

**Issue by Code-eat-sleep-include** [dvjsharma/Drawn2Shoe#47]
**The new feature**
I'll add the logo in the title, and fix the navbar. The signup button stays black when clicked. I'll change that, and make a better looking UI for the navbar.

**The possible approach**
Will add some cool hover effects in the navbar, and will add a logo.

**Comment by Code-eat-sleep-include** [comment]
@ShashankShekhar07 Kindly assign me this task!

**Comment by ShashankShekhar07** [comment]
Hey @Code-eat-sleep-include please go ahead
