### ISSUE TITLE
[Bug] Overflowing white background behind "Customize Now" button on the Home Page

### ISSUE THREAD

**Issue by Varad0014** [dvjsharma/Drawn2Shoe#48]
**Describe the bug**
Hi, if you carefully observe, there is an overflow of background in the "Customize Now" button. The white background is overflowing behind the button in hovered as well as non-hovered state. Also 

**Steps To Reproduce**
1. Go to "Customise Now" button on Home Page
2. See background behind button

**Expected behavior**
There should be no overflowing background.

**Screenshots**
Non-hovered state:
<img width="674" alt="button" src="https://github.com/dvjsharma/Drawn2Shoe/assets/77493105/6c533092-c2b0-47f4-a6ad-361b3b40c903">
Hovered state:
<img width="674" alt="button-hover" src="https://github.com/dvjsharma/Drawn2Shoe/assets/77493105/cc7f8f34-b993-44a3-b2e5-9876cef9e1c0">

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 
 **Additional context**
 I can fix this. Please assign this to me.

**Comment by Varad0014** [comment]
Also the text on the button is slightly asymmetrical vertically. I can rectify this by applying uniform padding along the vertical axis.

**Comment by ShashankShekhar07** [comment]
Hey @Varad0014 please go ahead
