### ISSUE TITLE
Adding a Payment gateway

### ISSUE THREAD

**Issue by mehtakevan** [dvjsharma/Drawn2Shoe#50]
**Describe the new feature**
Integrating the payment gateway in the website

**Describe the possible approach**
I will try to integrate razorpay payment gateway

**Describe any alternatives**
Alternatively I will try stripe payment gateway

**Comment by mehtakevan** [comment]
@dvjsharma Can you please assign this issue to me

**Comment by dvjsharma** [comment]
We already have a payment gateway @mehtakevan, but it has a few bugs. Would be helpful if you can fix them. WDYT?

**Comment by mehtakevan** [comment]
@dvjsharma Surely, I would like to work on that. Can you just brief me what bugs does it have.

**Comment by dvjsharma** [comment]
Hay @mehtakevan. One that I remember is gateway turn up even when it's not initiated. Other thing (related to auth) is the card is not connected to users as of now. Even if the user changes cart contents remain same. PTAL.

**Comment by mehtakevan** [comment]
@dvjsharma okay sure. I am interested in this issue. I will look into that and will try to fix the bugs

**Comment by dvjsharma** [comment]
Any updates @mehtakevan

**Comment by kaali001** [comment]
Hey @dvjsharma , Assign this issue to me, as I was working I noticed when user clicks on the cart button then issue arises, I would like to work on this also.

**Comment by dvjsharma** [comment]
Go ahead @kaali001

**Comment by kaali001** [comment]
> Hay @mehtakevan. One that I remember is gateway turn up even when it's not initiated. Other thing (related to auth) is the card is not connected to users as of now. Even if the user changes cart contents remain same. PTAL.

Hey @dvjsharma  ,  Your mentioned issues are already solved by someone,  #133 . so close this issue as done.

But the cart page have an issue that if no items in cart , then also the checkout cards rendering. so please let me know that I should solve this issue or I have to open another issue for this.

![image](https://github.com/user-attachments/assets/3a20ac46-ff52-4aae-88c0-1a4dcf635adf)

**Comment by dvjsharma** [comment]
Hey @kaali001. This, along with product addition and deletion issue is also there in cart. We can track track them in this ticket.

**Comment by kaali001** [comment]
Hey @dvjsharma , I have fixed the empty cart issue, for adding-decreasing the item number , it can be implemented by` /add` api, 
 But for removing an item I would have to create an api for `/remove` and also have to define remove-cart function in `server/controller `   ,  so it will give conflict to issue #117 . so I would suggest merge this #138  ORM  PR first.

**Comment by dvjsharma** [comment]
Closing against #148
