### ISSUE TITLE
Add Favicon.

### ISSUE THREAD

**Issue by SwanandD121** [dvjsharma/Drawn2Shoe#53]
**Problem**
The website lacks a favicon, which diminishes its professional appearance and branding consistency. A favicon is a small but essential element that appears in the browser tab and bookmarks, helping users quickly identify and navigate to the website.

**Solution**
Adding the favicon which will be the shoe image from the home banner component.

Please assign me this issue under GSSoC'24.

**Comment by ShashankShekhar07** [comment]
Hey @SwanandD121  Please Go ahead

**Comment by dvjsharma** [comment]
I think this is already being covered by #56

**Comment by ketanop321** [comment]
I can do this in minutes please assign this to me @SwanandD121
