### ISSUE TITLE
[Bug] Arrow keys present in pincode input of Signup page

### ISSUE THREAD

**Issue by Varad0014** [dvjsharma/Drawn2Shoe#54]
**Describe the bug**
The arrow keys which appear as default in the input of type 'number' are stil present in the pincode input field of Signup page.  These are used for increasing or decreasing number by one, which is not really necessary for pincode input field.

**Steps To Reproduce**
1. Go to Signup page
2. Click on pincode input in look at the right end of input box.

**Expected behavior**
The arrows should not be there as its not neccessary

**Screenshots**
<img width="623" alt="input-arrow" src="https://github.com/dvjsharma/Drawn2Shoe/assets/77493105/a531953d-1ab9-4266-85ea-ce983d68ac22">

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - Version Any

**Additional context**
I can remove those arrows from the box. Please assign this issue to me.

**Comment by ShashankShekhar07** [comment]
Hey @Varad0014 please go ahead
