### ISSUE TITLE
UI CHANGESS in the WEBSITE

### ISSUE THREAD

**Issue by venkat2295** [dvjsharma/Drawn2Shoe#62]
**Describe the new feature**
A clear and concise description of what the feature is
the UI in login and signup and customize form is too basic and login is also not working
**Describe the possible approach**
using glass effects we can enhance user experience  
**Describe any alternatives**
![image](https://github.com/dvjsharma/Drawn2Shoe/assets/118790430/29183dbc-c2b4-4d81-82ff-556c389d7b4b)
INTO THIS
![image](https://github.com/dvjsharma/Drawn2Shoe/assets/118790430/bda2507b-80e8-4683-929d-72c71b79ddb2)

**Additional context**
please assign me this issue i will also change login form 
@dcoder13 please assign me this

**Comment by dvjsharma** [comment]
Hey @Venkatknight2295. New changes looks good, but doesn't match with existing theme. Please explore other options and let us know.

**Comment by venkat2295** [comment]
The background can be changed

**Comment by dvjsharma** [comment]
A figma-design/samples would be helpful.

**Comment by dvjsharma** [comment]
Closing since no input is provided
