### ISSUE TITLE
[feat]: Back to top button 

### ISSUE THREAD

**Issue by Arghyadeep09** [dvjsharma/Drawn2Shoe#63]
**Describe the new feature**

The absence of a back-to-top button on the website significantly impairs its user-friendliness and navigational convenience, posing a notable problem in terms of user experience

**Describe the possible approach**
after scrolling to the extreme bottom of the page there must be a button which on click takes the user to the above of the webpage 

**Describe any alternatives**
A back to top button should be added to enhance user experience

**Additional context**
the button must be present there
![image](https://github.com/dvjsharma/Drawn2Shoe/assets/90449806/85dcd7d2-8efb-4197-a6c2-fd9526ebc1dc)

**Comment by prachita0504** [comment]
Under GSSOC 24, Please assign the work to me!

**Comment by dvjsharma** [comment]
Any updates @Arghyadeep09

**Comment by dvjsharma** [comment]
Please go ahead @prachita0504.
