### ISSUE TITLE
Auto Scroll to top when route changes

### ISSUE THREAD

**Issue by Sujal7ss** [dvjsharma/Drawn2Shoe#70]
**Description**:
When navigating between pages, the viewport should automatically scroll to the top of the new page.

**Current Behavior**:
Currently, when the user navigates to a new page, the viewport maintains the scroll position from the previous page.

**Expected Behavior**:
Upon changing pages, the viewport should start from the top of the new page.

**Proposed Solution**:
Implement an auto scroll to top feature when the route changes.

I am a GSSOC contributor.
@dvjsharma please assign this issue to me, along with required gssoc labels.

**Comment by dvjsharma** [comment]
Will be a good enhancement. Go ahead @Sujal7ss.
