### ISSUE TITLE
Mentor assignment

### ISSUE THREAD

**Issue by sharmavikas4** [dvjsharma/Drawn2Shoe#71]
Hello @dvjsharma myself Vikas Sharma, I am assigned as a mentor to your project. I have mailed you many times in this regard but no reply. Due to which i have to create this issue request. So I request you to provide me with the powers to label contributor issues, review their changes,

**Comment by dvjsharma** [comment]
Sorry @sharmavikas4. Please connect with me on discord, same username.

**Comment by sharmavikas4** [comment]
@dvjsharma i have sent a request to @dvjsharma  on discord. My username is @vikas04052003 . Please accept the request as soon as possible
