### ISSUE TITLE
Enhance Navbar sections

### ISSUE THREAD

**Issue by aasthakourav20** [dvjsharma/Drawn2Shoe#77]
Hey , I would like to enhance the navbar sections .
Kindly assign it to me under GSSoC'24.

**Comment by dvjsharma** [comment]
What specifically are you going to improve?

**Comment by aasthakourav20** [comment]
> What specifically are you going to improve?

I think the logo should not  be at center & we can add light/dark mode

![Screenshot (261)](https://github.com/dvjsharma/Drawn2Shoe/assets/148269962/9f37d664-2f31-4965-bcb1-59c0d2b2bf68)

**Comment by dvjsharma** [comment]
Logo was already centered until you added the 'About Us' section, and tracking for dark mode is already in progress at #57.

**Comment by dvjsharma** [comment]
Closing due to lack of input.
