### ISSUE TITLE
Problem in node modules, using deprecated bcrypt

### ISSUE THREAD

**Issue by Sujal7ss** [dvjsharma/Drawn2Shoe#79]
**Describe the bug**
the most importatnt step to run the development server is to install the dependencies using npm i.
But we are having issues because of the bcrypt module.

**Steps To Reproduce**
fork the repo 
cd client
npm i

**Expected behavior**
Change bcrypt to bcryptjs

<img width="777" alt="Screenshot 2024-06-01 120952" src="https://github.com/dvjsharma/Drawn2Shoe/assets/104003078/b32d4593-07c5-4701-96d2-52608c8e9b45">

**Desktop (please complete the following information):**
 - OS: Windows
 -  Chrome

**Comment by dvjsharma** [comment]
Makes sense @Sujal7ss. Go ahead. Make sure to migrate to non-depreciated versions only and make relevant code changes in auth files as well.
