### ISSUE TITLE
The homepage is having multiple errors

### ISSUE THREAD

**Issue by Sujal7ss** [dvjsharma/Drawn2Shoe#81]
**Describe the bug**
There are some issues of React like button tag is provided as an attribute, non-serializable value was detected and activeClassName is given as props which was not recognized.

**Steps To Reproduce**
At any page, open the inspection (dev tools) using CTRL+Shift+i

**Expected behavior**
No errors

**Screenshots**
<img width="853" alt="Screenshot 2024-06-01 144133" src="https://github.com/dvjsharma/Drawn2Shoe/assets/104003078/12bc9de6-625d-48eb-a7e4-931c418ef647">
<img width="850" alt="Screenshot 2024-06-01 144107 - Copy" src="https://github.com/dvjsharma/Drawn2Shoe/assets/104003078/6fcf67d8-482d-4832-9797-0911cc95da5d">

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome

**Comment by Sujal7ss** [comment]
In React Router v6, NavLink no longer accepts activeClassName. Instead, it uses a function for the className prop to determine the active state. @dvjsharma  Please assign this issue to me with suitable gssoc labels

**Comment by Sujal7ss** [comment]
The list Product card in Categories section should have unique key prop
<img width="904" alt="Screenshot 2024-06-01 151306" src="https://github.com/dvjsharma/Drawn2Shoe/assets/104003078/74122a5b-4d9e-4fd9-a5a9-a6de3a04b228">

**Comment by dvjsharma** [comment]
Go ahead @Sujal7ss. Currently adding level1, will change based on the scope of your PR.

**Comment by Sujal7ss** [comment]
There is a bug in shop section - 
If user adds a product without selecting the shoe size, but the cart api is expecting the shoe size and attempts to add size (undefined) . It crashes the server. 
Should i create new issue for this?? @dvjsharma

**Comment by Sujal7ss** [comment]
<img width="950" alt="Screenshot 2024-06-01 170050" src="https://github.com/dvjsharma/Drawn2Shoe/assets/104003078/5269fef3-932a-4652-953d-45cb39e227b7">

**Comment by dvjsharma** [comment]
Nice catch @Sujal7ss. We already tracked this one. Maybe fix it under this issue itself.

**Comment by Sujal7ss** [comment]
> Nice catch @Sujal7ss. We already tracked this one. Maybe fix it under this issue itself.

But it will be more difficult to assign the labels for this different kind of issues, so im creating a new issue for this please assign that to me
