### ISSUE TITLE
Server Crash due to undefined value is sent to addCart api

### ISSUE THREAD

**Issue by Sujal7ss** [dvjsharma/Drawn2Shoe#84]
**Describe the bug**
There is a bug in shop section -
If user adds a product without selecting the shoe size, but the cart api is expecting the shoe size and attempts to add size (undefined) . It crashes the server.

**Steps To Reproduce**
1. Log in to the website
2. Select any product
3. Add to cart without selecting the shoe size

**Expected behavior**
A error message must be shown to user to select a shoe size

<img width="950" alt="Screenshot 2024-06-01 170050" src="https://github.com/dvjsharma/Drawn2Shoe/assets/104003078/25453da4-1d4c-45bc-b1ff-1c1cef5bdab7">

**Comment by Sujal7ss** [comment]
@dvjsharma Please assign me this issue. Suggest any changes if required..

**Comment by dvjsharma** [comment]
Approach looks good. We are already using `react-hot-toast` library for notifications. Please see if you can implement a validation throws a prompt when no size is selected.

**Comment by Sujal7ss** [comment]
Okay I will use it 
It's an enhancement to previous feature, can you add level 2

**Comment by dvjsharma** [comment]
It’s a basic check. Level 1 seems good. 
//cc @ShashankShekhar07

**Comment by Sujal7ss** [comment]
> Approach looks good. We are already using `react-hot-toast` library for notifications. Please see if you can implement a validation throws a prompt when no size is selected.

It was added 
![Screenshot 2024-06-08 015705](https://github.com/dvjsharma/Drawn2Shoe/assets/104003078/9b64a680-878a-4d80-89f9-f922c3106552)

**Comment by dvjsharma** [comment]
PR was WIP when I saw it. Please rename as tests are failing

**Comment by Sujal7ss** [comment]
How should I rename it, what is causing the title checker failed issue
