### ISSUE TITLE
The website is getting horizontal bar. With that the animation doesn't look cool.

### ISSUE THREAD

**Issue by mohit-bhandari45** [dvjsharma/Drawn2Shoe#87]
**Describe the bug**
So as I can see the home page of the website is getting horizontal bar, and the ui can be enhanced by adding animations and more.

**Steps To Reproduce**
1. Go to Home page
2. AN directly see the horizontal bar

**Expected behavior**
The bar should be removed and multiple animations can be done.

**Screenshots**
![image](https://github.com/dvjsharma/Drawn2Shoe/assets/151373021/79b7fb89-08d1-4c88-97a2-02b8867e3205)

I want to work on this issue under gssoc24. Just add a level2 label to it.

**Comment by sharmavikas4** [comment]
@mohit-bhandari45 the issue you have looks like a minor bug and i can label it level 1. The level 2 requires a bug fix that is causing some problem in the functionality. These small ui related bugs are labeled as level 1. so i can label it as level 1. If you have any query feel free to share

**Comment by mohit-bhandari45** [comment]
Ok sure raised a pr you can check.
But I also changed some ui animations of the website
