### ISSUE TITLE
Redesign the logo of the website.

### ISSUE THREAD

**Issue by saniahussain7** [dvjsharma/Drawn2Shoe#94]
Hey!! I am a GSSoC contributor and i want to redesign the logo of Drawn2shoe .

![Screenshot 2024-06-04 144011](https://github.com/dvjsharma/Drawn2Shoe/assets/153106882/a4b558a2-3740-4d31-8040-7c700efd649c)

 Since an appealing logo for good branding is a need nowadays therefore i would like to give it a new look.
Can you please give me a chance and assign this issue to me?

**Comment by saniahussain7** [comment]
@dvjsharma ??

**Comment by dvjsharma** [comment]
I think this already looks fine and servers the purpose well. Instead, I would suggest redesigning this [logo](https://github.com/dvjsharma/Drawn2Shoe/blob/master/client/src/assets/logo-final.png). WDYT?

**Comment by saniahussain7** [comment]
Sure, I will redesign it and update you on this issue soon. Thank you for giving me this opportunity .

**Comment by saniahussain7** [comment]
hey @dvjsharma, I have come with certain logo designs for it. would you like to take a look on them or should I directly raise a pull request for it?

**Comment by dvjsharma** [comment]
I’ll suggest adding them on website, taking a screenshot and sharing them on google drive before the PR so we can work on changes if required.

**Comment by saniahussain7** [comment]
okay

**Comment by dvjsharma** [comment]
any updates @saniahussain7?

**Comment by saniahussain7** [comment]
Sorry for the delay,I have changed the Logos here are some design.
https://docs.google.com/document/d/1Mm8ZF-sR9Q_e9JMG1i0YNX3trU-YG4CvSSNsDgMCMGc/edit?usp=sharing
Looking Forward to ur suggestions.

**Comment by dvjsharma** [comment]
Cc @ShashankShekhar07

**Comment by ShashankShekhar07** [comment]
Hey @saniahussain7 thank you for your efforts but I think we are gonna stick with the previous logo only.

**Comment by dvjsharma** [comment]
Feel free to work on other issues @saniahussain7
